version: "3.8"

services:
  hc-bssn-ws-insecure-api-db:
    image: postgres:15-alpine
    restart: always
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
      - POSTGRES_DB=insecuredb
    ports:
      - "5432:5432"
    volumes:
      - hc-bssn-ws-insecure-api-pgdata:/var/lib/postgresql/data
    networks:
      - app-network

volumes:
  hc-bssn-ws-insecure-api-pgdata:

networks:
  app-network:
    driver: bridge
